# This file was generated by GoReleaser. DO NOT EDIT.
cask "driverforge" do
  version "0.6.1"

  on_macos do
    on_intel do
      sha256 "85586635c15cf8ebc4c5ce6ad13f8459822ee852385a280c8be9de02f2a4fa7e"
      url "https://releases.driverforge.com/driverforge-releases/driverforge-cli/v#{version}/driverforge_#{version}_darwin_amd64.tar.gz",
        verified: "releases.driverforge.com/driverforge-releases/driverforge-cli/"
    end
    on_arm do
      sha256 "8c9f84915779a5ae1ab84ba65fbc0054cff5e5ff81bd4106e4f6fc45c66c3cf6"
      url "https://releases.driverforge.com/driverforge-releases/driverforge-cli/v#{version}/driverforge_#{version}_darwin_arm64.tar.gz",
        verified: "releases.driverforge.com/driverforge-releases/driverforge-cli/"
    end
  end

  on_linux do
    on_intel do
      sha256 "99c217d01dba9920708cf14f822057254f815bc9603e453f240b1515f25158af"
      url "https://releases.driverforge.com/driverforge-releases/driverforge-cli/v#{version}/driverforge_#{version}_linux_amd64.tar.gz",
        verified: "releases.driverforge.com/driverforge-releases/driverforge-cli/"
    end
    on_arm do
      sha256 "4eb91fd6abe80ab24b6d0bf474e3132a0575b99b421d41b603ccac02e4f77f60"
      url "https://releases.driverforge.com/driverforge-releases/driverforge-cli/v#{version}/driverforge_#{version}_linux_arm64.tar.gz",
        verified: "releases.driverforge.com/driverforge-releases/driverforge-cli/"
    end
  end

  name "driverforge"
  desc "Driverforge CLI — build and manage Control4 drivers"
  homepage "https://go.driverforge.com/app"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "driverforge"

  postflight do
    # Unsigned build: remove the quarantine flag so Gatekeeper allows the binary.
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/driverforge"]
    end
  end

  # No zap stanza required

end
