# This file was generated by GoReleaser. DO NOT EDIT.
cask "driverforge" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "751a0429339257fc4e8312830925fcd338eaf86d4a26b8081ede67a26f800105"
      url "https://releases.driverforge.com/driverforge-releases/driverforge-cli/v#{version}/driverforge_#{version}_darwin_amd64.tar.gz",
        verified: "releases.driverforge.com/driverforge-releases/driverforge-cli/"
    end
    on_arm do
      sha256 "754c324facac1d03930d3142f97c7666625d05efb814b2cbdba78f733dcbb191"
      url "https://releases.driverforge.com/driverforge-releases/driverforge-cli/v#{version}/driverforge_#{version}_darwin_arm64.tar.gz",
        verified: "releases.driverforge.com/driverforge-releases/driverforge-cli/"
    end
  end

  on_linux do
    on_intel do
      sha256 "fee4c48fba14eb21bec6a9dc758d3d4ad8c7e5f78656151e8cbe51849b36c511"
      url "https://releases.driverforge.com/driverforge-releases/driverforge-cli/v#{version}/driverforge_#{version}_linux_amd64.tar.gz",
        verified: "releases.driverforge.com/driverforge-releases/driverforge-cli/"
    end
    on_arm do
      sha256 "1fdad4618fbd7a1443a84f20d8c3b6766bd77b13d9210bc09048b84ac96afa05"
      url "https://releases.driverforge.com/driverforge-releases/driverforge-cli/v#{version}/driverforge_#{version}_linux_arm64.tar.gz",
        verified: "releases.driverforge.com/driverforge-releases/driverforge-cli/"
    end
  end

  name "driverforge"
  desc "Driverforge CLI — build and manage Control4 drivers"
  homepage "https://driverforge.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "driverforge"

  postflight do
    # Unsigned build: remove the quarantine flag so Gatekeeper allows the binary.
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/driverforge"]
    end
  end

  # No zap stanza required

end
