# This file was generated by GoReleaser. DO NOT EDIT.
cask "driverforge" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "fcbb7226534976bdb4db16ea9d2220f8e3e97869a1ceec941408565c74b2cfbe"
      url "https://releases.driverforge.com/driverforge-releases/driverforge-cli/v#{version}/driverforge_#{version}_darwin_amd64.tar.gz",
        verified: "releases.driverforge.com/driverforge-releases/driverforge-cli/"
    end
    on_arm do
      sha256 "16c864c6895a0d2e93e8b942a71c9e7ffedd21a82708d040d882017ca4a55d52"
      url "https://releases.driverforge.com/driverforge-releases/driverforge-cli/v#{version}/driverforge_#{version}_darwin_arm64.tar.gz",
        verified: "releases.driverforge.com/driverforge-releases/driverforge-cli/"
    end
  end

  on_linux do
    on_intel do
      sha256 "86639d425c86a34f97b0e13f9a9b3f243b13b0c9e09ed2eddfe3e1d32c0771a2"
      url "https://releases.driverforge.com/driverforge-releases/driverforge-cli/v#{version}/driverforge_#{version}_linux_amd64.tar.gz",
        verified: "releases.driverforge.com/driverforge-releases/driverforge-cli/"
    end
    on_arm do
      sha256 "104246ecb0d4e5bc1eada2f365ca2644a3beeaeb823fe27a1e32dd1be3930b37"
      url "https://releases.driverforge.com/driverforge-releases/driverforge-cli/v#{version}/driverforge_#{version}_linux_arm64.tar.gz",
        verified: "releases.driverforge.com/driverforge-releases/driverforge-cli/"
    end
  end

  name "driverforge"
  desc "Driverforge CLI — build and manage Control4 drivers"
  homepage "https://driverforge.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "driverforge"

  postflight do
    # Unsigned build: remove the quarantine flag so Gatekeeper allows the binary.
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/driverforge"]
    end
  end

  # No zap stanza required

end
