# This file was generated by GoReleaser. DO NOT EDIT.
cask "gayle" do
  version "6.1.0"

  on_macos do
    on_intel do
      sha256 "be93f3388ba5620becfd8c85693f1d51cc533afff1c3ccf8f492aabfccab42e0"
      url "https://releases.driverforge.com/driverforge-releases/gayle/v#{version}/gayle_#{version}_darwin_amd64.tar.gz",
        verified: "releases.driverforge.com/driverforge-releases/gayle/"
    end
    on_arm do
      sha256 "c170135e488d59332085cc09f11d074c6afc6793243ef13d5c7f9ddf57218750"
      url "https://releases.driverforge.com/driverforge-releases/gayle/v#{version}/gayle_#{version}_darwin_arm64.tar.gz",
        verified: "releases.driverforge.com/driverforge-releases/gayle/"
    end
  end

  on_linux do
    on_intel do
      sha256 "62ddfc162a5068838d27221380ba6c71108ee6f8fb158b9c7b3217bec69c2bf1"
      url "https://releases.driverforge.com/driverforge-releases/gayle/v#{version}/gayle_#{version}_linux_amd64.tar.gz",
        verified: "releases.driverforge.com/driverforge-releases/gayle/"
    end
    on_arm do
      sha256 "1adfa013a3df8c2f0025af4559ecb6852b6902e29983e86b401d0439760520ca"
      url "https://releases.driverforge.com/driverforge-releases/gayle/v#{version}/gayle_#{version}_linux_arm64.tar.gz",
        verified: "releases.driverforge.com/driverforge-releases/gayle/"
    end
  end

  name "gayle"
  desc "Deploy configuration and secrets to AWS SSM Parameter Store or Azure Key Vault"
  homepage "https://github.com/driverforge/gayle"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gayle"

  postflight do
    # Unsigned build: remove the quarantine flag so Gatekeeper allows the binary.
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gayle"]
    end
  end

  # No zap stanza required

end
