# This file was generated by GoReleaser. DO NOT EDIT.
cask "gayle" do
  version "6.1.1"

  on_macos do
    on_intel do
      sha256 "8dab4c1bc4b62dedf491acb6a976413cf85e6ec6a84d64bde33793eb4da81653"
      url "https://releases.driverforge.com/driverforge-releases/gayle/v#{version}/gayle_#{version}_darwin_amd64.tar.gz",
        verified: "releases.driverforge.com/driverforge-releases/gayle/"
    end
    on_arm do
      sha256 "a6cdce71315cc721699cf53cc45826178222a223999bda047ba4493276558b9f"
      url "https://releases.driverforge.com/driverforge-releases/gayle/v#{version}/gayle_#{version}_darwin_arm64.tar.gz",
        verified: "releases.driverforge.com/driverforge-releases/gayle/"
    end
  end

  on_linux do
    on_intel do
      sha256 "d072fca1d5990ca37c9a7df7b1a37f78c70e56760fc42f957eeb9e86b6dc7305"
      url "https://releases.driverforge.com/driverforge-releases/gayle/v#{version}/gayle_#{version}_linux_amd64.tar.gz",
        verified: "releases.driverforge.com/driverforge-releases/gayle/"
    end
    on_arm do
      sha256 "804fa1ad3e0f8c358dc8523f048124eb2c8c0734ebbc2d17a8c4799213211207"
      url "https://releases.driverforge.com/driverforge-releases/gayle/v#{version}/gayle_#{version}_linux_arm64.tar.gz",
        verified: "releases.driverforge.com/driverforge-releases/gayle/"
    end
  end

  name "gayle"
  desc "Deploy configuration and secrets to AWS SSM Parameter Store or Azure Key Vault"
  homepage "https://github.com/driverforge/gayle"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gayle"

  postflight do
    # Unsigned build: remove the quarantine flag so Gatekeeper allows the binary.
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gayle"]
    end
  end

  # No zap stanza required

end
