# This file was generated by GoReleaser. DO NOT EDIT.
cask "gayle" do
  version "6.0.1"

  on_macos do
    on_intel do
      sha256 "15a4017df9a5b0057aa2ed9dd2cac32c0026564bbad9f2467ef7ede74d6380f5"
      url "https://releases.driverforge.com/driverforge-releases/gayle/v#{version}/gayle_#{version}_darwin_amd64.tar.gz",
        verified: "releases.driverforge.com/driverforge-releases/gayle/"
    end
    on_arm do
      sha256 "ae7e12947752cacf4bc3dd8e7c1a2a54562d78f59712bd4037330f4b7a44f3e5"
      url "https://releases.driverforge.com/driverforge-releases/gayle/v#{version}/gayle_#{version}_darwin_arm64.tar.gz",
        verified: "releases.driverforge.com/driverforge-releases/gayle/"
    end
  end

  on_linux do
    on_intel do
      sha256 "6827adb276edd0f149887d30bade0ed66c235b5fe523a5fae5f62e0114700450"
      url "https://releases.driverforge.com/driverforge-releases/gayle/v#{version}/gayle_#{version}_linux_amd64.tar.gz",
        verified: "releases.driverforge.com/driverforge-releases/gayle/"
    end
    on_arm do
      sha256 "218e3530aca5800d7271c09d3c83353cbbd6bef2f993f3ecffe92128383e8871"
      url "https://releases.driverforge.com/driverforge-releases/gayle/v#{version}/gayle_#{version}_linux_arm64.tar.gz",
        verified: "releases.driverforge.com/driverforge-releases/gayle/"
    end
  end

  name "gayle"
  desc "Deploy configuration and secrets to AWS SSM Parameter Store or Azure Key Vault"
  homepage "https://github.com/driverforge/gayle"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gayle"

  postflight do
    # Unsigned build: remove the quarantine flag so Gatekeeper allows the binary.
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gayle"]
    end
  end

  # No zap stanza required

end
